### PR TITLE
Remove prefix 'v' from version name

### PR DESCRIPTION
**Pull request by rds13**
At least to support stable release version 2_1_1 of  iTerm2.
This allow specifiying version name in hiera.

### CODE REVIEW

**Comment by tarebyte** [comment]
@rds13 this looks fine to me, would you mind checking out why the tests are failing. Thanks!

**Comment by rds13** [comment]
Test fixed !

**Comment by rds13** [comment]
@tarebyte :+1:

**Comment by tarebyte** [comment]
Thanks @rds13!

**Pull request merged**
